### PR TITLE
ToJson and FromJson instances for S3Uri

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
I don't think these instances should exist. They are very opinionated this way. 

For example, why not `{"bucket": "blah", "objectKey": "blah"}`? This is also somehow canonical, S3/SQS messages have it this way...

I think the way it is serialised to JSON is very application-specific and should sit with the application.

**Comment by newhoggy** [comment]
I think if you wanted that you just create a type with a `bucket` field and an `objectKey` field and write the codecs for the new type.

The reason I believe this instance make sense is that every time we've had a field of the type `S3Uri` we've wanted it encoded this way without exception.

**Comment by AlexeyRaga** [comment]
`S3Uri` _is_ that type with a `bucket` and `objectKey` fields, it'd be weird to ask to create another one ;)

I think if you wanted a string, you'd just call `toText` on this type, and you don't need these instances. Same goes for parsing: `fromText` is already there.

**Comment by newhoggy** [comment]
I'm talking about records like

```
data Message = Message
   { source :: S3Uri
   , target :: S3Uri
   , command :: Text
   } deriving (Eq, Show, Generic, ToJSON, FromJSON
```

**Comment by AlexeyRaga** [comment]
```
instance ToJSON Message where
  toJSON r = object 
    [ "source" .= toText (source r)
    , "target" .= toText (target r)
    , "command" .= command r
    ]
```

No problems here

**Comment by newhoggy** [comment]
What about the `FromJSON`?

**Comment by AlexeyRaga** [comment]
I see no problems here either

```
instance FromJSON Message where
  parseJSON = withObject "message" $ \o -> Message 
    <$> (o .: "source" <&> fromText)
    <*> fmap fromText (o .: "target")
    <*> o .: "command"
```

or whatever notation you prefer ;)

**Comment by AlexeyRaga** [comment]
Oops, perhaps you'd want `.:?` instead of `.:` because of maybyness...

**Comment by newhoggy** [comment]
I've modified it to use `fromText` instead to avoid conversion to `String`.

**Comment by newhoggy** [comment]
The problem here is `FromJSON` is much more error prone to write and lots of jobs that ought to decode it the same way end up doing it subtly differently.

I believe this is one place where having an actual instance makes a lot of sense.

**Comment by newhoggy** [comment]
It's not as straight foward as you describe:

```
src/Antiope/S3/Types.hs:108:10: error:
    • Couldn't match type ‘Either String a0’ with ‘S3Uri’
      Expected type: J.Parser S3Uri
        Actual type: J.Parser (Either String a0)
    • In the second argument of ‘(<$>)’, namely
        ‘(o .: "source" <&> fromText)’
      In the first argument of ‘(<*>)’, namely
        ‘Message <$> (o .: "source" <&> fromText)’
      In the first argument of ‘(<*>)’, namely
        ‘Message <$> (o .: "source" <&> fromText)
           <*> fmap fromText (o .: "target")’
    |
108 |     <$> (o .: "source" <&> fromText)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by newhoggy** [comment]
If `fromText` was `Text -> S3Uri` it would compile, but it would be partial and wrong.

**Comment by newhoggy** [comment]
I've been hesitant to add this instance for a long time because my problem with it was to add a dependency on `aeson`, which is pretty heavyweight, but then I checked and found we already pay for this dependency anyway.

**Comment by AlexeyRaga** [comment]
Still, my problem is not with how it is implemented. My problem is in the fact that these instances exist. And in the fact that they exist for one specific use case only.

For the same reason I haven't implemented "canonical" `ToJSON/FromJSON`  (`{"bucket": "blah", "objectKey": "blah"}`) in the first place. There is already a use case for that too, but I feel that prioritising one app-specific use case over another is wrong.

You can definitely make it work, maybe with `.:?` as I suggested, I don't remember. I can have a look tomorrow.
But I really don't want to give S3Uri string'ish instance just because it is sometimes convenient to encode them as strings...

**Comment by newhoggy** [comment]
I don't see a legitimate reason to support the structure `{"bucket": "blah", "objectKey": "blah"}` except if you wanted to do something like this:

`{"bucket": "blah", "objectKey": "blah", "objectKey2", "blah"}`

But if you did, you could just do this:

```
data Record = Record
  { bucket :: Bucket
  , objectKey1 :: ObjectKey
  , objectKey2 :: ObjectKey
  } deriving (Eq, Show, Generic, ToJSON, FromJSON)
```

Having an `S3Uri` instance doesn't actually get in the way.

**Comment by newhoggy** [comment]
In this case the uri representation is actually the most appropriate because the word uri is in the name.

We ought to have another type that serialises to the format you describe with a name that doesn't include the word URI.

**Pull request merged**
